# This is a basic workflow to help you get started with Actions

name: CI Test


on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, arm] 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      - name: Clone einfachIT/ansible-collection-epic repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: einfachIT/ansible-collection-epic
          path: einfachit.epic
      
      - name: Run molecule tests
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY}}
        run: |
          source source.me
          echo "$VAULT_KEY" > .vault
          ansible-galaxy collection install -f ./einfachit.epic
          ansible-playbook -i inventory_acc.yml --extra-var project_dir=$(pwd) einfachit.epic.decommission_container
          ansible-playbook -i inventory_acc.yml einfachit.epic.decommission_raspberries
          ansible-playbook -i inventory_acc.yml einfachit.epic.provision_raspberries
          ansible-playbook -i inventory_acc.yml einfachit.epic.configure_server
          ansible-playbook -i inventory_acc.yml einfachit.epic.configure_epicraspberries
          ansible-playbook -i inventory_acc.yml --extra-var project_dir=$(pwd) einfachit.epic.provision_container
          ansible-playbook -i inventory_acc.yml --extra-var @users_acc.yml --extra-var project_dir=$(pwd) --extra-var @secrets_acc.yml einfachit.epic.configure_container
