# This is a basic workflow to help you get started with Actions

name: CI Test


on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64] 
    steps:
      - uses: actions/checkout@v2
          
      - name: Clone einfachIT/ansible-collection-epic repository
        uses: actions/checkout@v2
        with:
          repository: einfachIT/ansible-collection-epic
          path: einfachit.epic
      
      - name: Run molecule tests
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY}}
        run: |
          sudo apt-get -y install python3-venv
          source source.me
          echo "$VAULT_KEY" > .vault
          ansible-galaxy collection install -f ./einfachit.epic
          ansible-galaxy install -f bassinator.localisation
          ansible-playbook -i inventory_acc.yml einfachit.epic.poweron_raspberries.yml
          sleep 60
          ansible-playbook -i inventory_acc.yml	einfachit.epic.poweron
          ansible-playbook -i inventory_acc.yml --extra-var project_dir=$(pwd) einfachit.epic.decommission_container
          ansible-playbook -i inventory_acc.yml einfachit.epic.decommission_raspberries
          ansible-playbook -i inventory_acc.yml einfachit.epic.provision_raspberries
          ansible-playbook -i inventory_acc.yml -vvv einfachit.epic.configure_server
          ansible-playbook -i inventory_acc.yml einfachit.epic.configure_epicraspberries
          ansible-playbook -i inventory_acc.yml --extra-var project_dir=$(pwd) einfachit.epic.provision_container
          ansible-playbook -i inventory_acc.yml -vvv --extra-var @users_acc.yml --extra-var project_dir=$(pwd) --extra-var @secrets_acc.yml einfachit.epic.configure_epicbackup
          ansible-playbook -i inventory_acc.yml --extra-var @secrets_acc.yml verify.yml
          ansible -i inventory_acc.yml raspberries -a "/sbin/shutdown -h +1" --become
          sleep 90
          ansible-playbook -i inventory_acc.yml einfachit.epic.poweroff_raspberries.yml
