# This is a basic workflow to help you get started with Actions

name: Publish release

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
